FROM postgres:9.5

ENV PG_EXTENSION_DIR /usr/share/postgresql/9.5/extension/

RUN apt-get update -y && apt-get install -y postgresql-9.5-postgis-3 cmake libpq-dev postgresql-server-dev-9.5 zip unzip python3-pip
